version: "3.9"

services:
  mariadb:
    hostname: mariadb
    image: mariadb:10.11.7-jammy
    volumes:
      - ./data:/var/lib/mysql:rw
    restart: always
    environment:
      MARIADB_USER: ${SQL_USER}
      MARIADB_PASSWORD: ${SQL_PASSWORD}
    env_file:
      - .env

  bot:
    hostname: bot
    image: ghcr.io/justalemon/leek:latest
    depends_on:
      mariadb:
        condition: service_started
    environment:
      SQL_HOST: mariadb
      SQL_DB: leek
    env_file:
      - .env
